//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChartMarkWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Brand
    {
        public string brandID { get; set; }
        public string brandName { get; set; }
        public string nation { get; set; }
    }
}
