//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChartMarkWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HeadPhone
    {
        public int ID { get; set; }
        public string headphoneID { get; set; }
        public string name { get; set; }
        public string brandId { get; set; }
        public string category { get; set; }
        public string type { get; set; }
        public string micro { get; set; }
        public string jack { get; set; }
        public string frequencyRange { get; set; }
        public string bluetooth { get; set; }
        public Nullable<double> length { get; set; }
        public Nullable<int> averagePrice { get; set; }
        public string image1 { get; set; }
        public string image2 { get; set; }
        public string image3 { get; set; }
    }
}
