//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChartMarkWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Laptop
    {
        public int ID { get; set; }
        public string laptopID { get; set; }
        public string name { get; set; }
        public string brandId { get; set; }
        public string category { get; set; }
        public string type { get; set; }
        public Nullable<int> year { get; set; }
        public string chip { get; set; }
        public string ram { get; set; }
        public string rom { get; set; }
        public Nullable<double> screenSize { get; set; }
        public string webcam { get; set; }
        public string wifi { get; set; }
        public string OS { get; set; }
        public Nullable<double> weight { get; set; }
        public string battery { get; set; }
        public Nullable<int> averagePrice { get; set; }
        public string image1 { get; set; }
        public string image2 { get; set; }
        public string image3 { get; set; }
    }
}
